"""
Change Set Consistency Validator — Sprint 8.

Runs deterministic pre-verification checks against an EngineeringChangeSet
to detect contract mismatches before any mutation occurs.

Checks include:
- Definition changed but no caller in the change set
- Exported symbol removed but import still present in repo
- Renamed configuration key still referenced elsewhere
- Interface changed but no implementation update
- Schema changed but migration absent
- New file missing from package configuration
- Moved module still imported via old path
- Generated source stale (direct edit without regeneration)
- Duplicate old+new implementation coexistence
- Missing test change for a functional change

All checks are deterministic — no boolean-only results. Produces a typed
ChangeSetValidationResult with full lists of missing changes, stale references,
contract mismatches, and scope violations.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from nexus.multifile.contracts import (
    ChangeType,
    ChangeSetValidationResult,
    ContractMismatch,
    EngineeringChangeSet,
    ImpactCategory,
    MissingChange,
    Reference,
    ScopeViolation,
    ValidationStatus,
)

logger = logging.getLogger(__name__)

# Files/dirs that are always protected from mutation
_PROTECTED_PATHS = frozenset({
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "SECURITY.md",
    "LICENSE",
    ".github/CODEOWNERS",
})


class ChangeSetConsistencyValidator:
    """Validates an EngineeringChangeSet for internal consistency before execution."""

    def __init__(self, repo_root: str | Path) -> None:
        self.repo_root = Path(repo_root)

    def validate(self, cs: EngineeringChangeSet) -> ChangeSetValidationResult:
        result = ChangeSetValidationResult(status=ValidationStatus.PASS)

        self._check_unexplained_files(cs, result)
        self._check_protected_paths(cs, result)
        self._check_generated_direct_edits(cs, result)
        self._check_stale_callers(cs, result)
        self._check_stale_imports_after_delete_or_move(cs, result)
        self._check_schema_without_migration(cs, result)
        self._check_new_file_in_package(cs, result)
        self._check_missing_test_changes(cs, result)

        if (
            result.missing_changes
            or result.stale_references
            or result.contract_mismatches
            or result.scope_violations
        ):
            result.status = ValidationStatus.FAIL

        return result

    # ------------------------------------------------------------------
    # Individual checks
    # ------------------------------------------------------------------

    def _check_unexplained_files(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """Every file in the change set must have a non-empty reason."""
        for fc in cs.file_changes:
            if not fc.reason.strip():
                result.scope_violations.append(
                    ScopeViolation(
                        path=fc.path,
                        reason="File has no stated reason for inclusion in the change set.",
                        violation_type="UNEXPLAINED",
                    )
                )

    def _check_protected_paths(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """Protected paths require explicit protection=True on the PlannedFileChange."""
        for fc in cs.file_changes:
            is_protected = (
                fc.path in _PROTECTED_PATHS
                or any(fc.path.startswith(p) for p in _PROTECTED_PATHS if p.endswith("/"))
            )
            if is_protected and not fc.protected:
                result.scope_violations.append(
                    ScopeViolation(
                        path=fc.path,
                        reason=f"'{fc.path}' is a protected path and requires explicit approval.",
                        violation_type="PROTECTED",
                    )
                )

    def _check_generated_direct_edits(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """Direct edits to generated files are rejected unless explicitly approved."""
        generated_markers = (
            "# This file is auto-generated",
            "# DO NOT EDIT",
            "# Generated by",
            "# Auto-generated",
            "// This file is auto-generated",
            "// DO NOT EDIT",
        )
        for fc in cs.file_changes:
            if fc.generated:
                # Allowed — the PlannedFileChange explicitly marks it generated
                continue
            # Check file header for generated markers
            full_path = self.repo_root / fc.path
            if full_path.is_file():
                try:
                    header = full_path.read_text(encoding="utf-8", errors="replace")[:500]
                    if any(marker in header for marker in generated_markers):
                        result.scope_violations.append(
                            ScopeViolation(
                                path=fc.path,
                                reason=(
                                    f"'{fc.path}' appears to be auto-generated. "
                                    "Modify the source generator instead, or set generated=True to acknowledge."
                                ),
                                violation_type="GENERATED",
                            )
                        )
                except OSError:
                    pass

    def _check_stale_callers(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """For each contract change, verify that known callers are in the change set."""
        change_set_paths = {fc.path for fc in cs.file_changes}

        for cc in cs.contract_changes:
            for consumer in cc.consumers:
                if consumer.path and consumer.path not in change_set_paths:
                    result.missing_changes.append(
                        MissingChange(
                            path=consumer.path,
                            reason=(
                                f"Known consumer of changed contract '{cc.contract_id}' "
                                f"is not included in the change set."
                            ),
                            category=ImpactCategory.MUST_CHANGE,
                            related_change=cc.definition.path,
                        )
                    )

    def _check_stale_imports_after_delete_or_move(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """After a DELETE or MOVE/RENAME, the old import path must not remain."""
        for fc in cs.file_changes:
            if fc.change_type not in (ChangeType.DELETE, ChangeType.MOVE, ChangeType.RENAME):
                continue

            old_module = fc.path.replace("/", ".").replace("\\", ".").removesuffix(".py")
            stale_files = self._find_files_importing(old_module)

            for stale_path in stale_files:
                if stale_path not in {fc2.path for fc2 in cs.file_changes}:
                    result.stale_references.append(
                        Reference(
                            path=stale_path,
                            symbol=old_module,
                            description=(
                                f"File imports '{old_module}' which has been "
                                f"{fc.change_type.value.lower()} but the import was not updated."
                            ),
                        )
                    )

    def _check_schema_without_migration(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """Schema changes should be accompanied by a migration file."""
        schema_changes = [
            fc for fc in cs.file_changes
            if fc.change_type == ChangeType.SCHEMA_CHANGE
        ]
        migration_paths = [
            fc.path for fc in cs.file_changes
            if fc.change_type == ChangeType.MIGRATION
        ]

        for sc in schema_changes:
            if not migration_paths:
                result.missing_changes.append(
                    MissingChange(
                        path="migrations/",
                        reason=(
                            f"Schema change in '{sc.path}' has no corresponding migration file."
                        ),
                        category=ImpactCategory.MUST_CHANGE,
                        related_change=sc.path,
                    )
                )
                result.warnings.append(
                    f"Schema change in '{sc.path}' detected without a migration file. "
                    "Add a MIGRATION-type change or explicitly acknowledge."
                )

    def _check_new_file_in_package(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """New Python files should have their package __init__.py in the change set."""
        existing_paths = {fc.path for fc in cs.file_changes}

        for fc in cs.file_changes:
            if fc.change_type != ChangeType.CREATE:
                continue
            if not fc.path.endswith(".py"):
                continue

            # Find the package __init__.py
            parent_init = str(Path(fc.path).parent / "__init__.py")
            full_init = self.repo_root / parent_init

            # If __init__ exists and is NOT in the change set → note as warning
            if full_init.exists() and parent_init not in existing_paths:
                result.warnings.append(
                    f"New file '{fc.path}' created in package '{Path(fc.path).parent}' "
                    f"but '{parent_init}' is not in the change set. "
                    "Verify exports are updated."
                )

    def _check_missing_test_changes(
        self, cs: EngineeringChangeSet, result: ChangeSetValidationResult
    ) -> None:
        """Functional changes (MODIFY, CREATE) should include test changes."""
        functional_changes = [
            fc for fc in cs.file_changes
            if fc.change_type in (ChangeType.MODIFY, ChangeType.CREATE)
            and not any(
                part in fc.path for part in ("test_", "/tests/", "test/", "_test.py")
            )
            and not fc.path.endswith((".md", ".yaml", ".yml", ".toml", ".json"))
        ]

        test_changes = [
            fc for fc in cs.file_changes
            if any(part in fc.path for part in ("test_", "/tests/", "test/", "_test.py"))
            or fc.change_type == ChangeType.TEST_CHANGE
        ]

        if functional_changes and not test_changes:
            result.warnings.append(
                f"Change set has {len(functional_changes)} functional file change(s) "
                "but no test changes. Verify tests are covered by existing test suite."
            )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _find_files_importing(self, module_name: str) -> list[str]:
        """Find Python files that import the given module name."""
        results: list[str] = []
        pattern = re.compile(
            rf"(?:from|import)\s+{re.escape(module_name)}(?:\s|\.|\Z)"
        )

        for py_file in self.repo_root.rglob("*.py"):
            rel = str(py_file.relative_to(self.repo_root))
            if ".venv" in rel or "__pycache__" in rel:
                continue
            try:
                content = py_file.read_text(encoding="utf-8", errors="replace")
                if pattern.search(content):
                    results.append(rel)
            except OSError:
                pass

        return results
